name: Automatizacion Biblioteca

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ejecutar-python:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Ejecutar sistema biblioteca
        run: python main.py